### ISSUE TITLE
Ubuntu 64 bit with ELFCLASS43 mismatch

### ISSUE THREAD

**Issue by tmiele** [nullpomino/nullpomino#50]
```console
$ ./NullpoMino
18:01:03,741 [main] INFO  NullpoMinoSlick: NullpoMinoSlick Start
OpenJDK 64-Bit Server VM warning: You have loaded library $PATH/NullpoMino7_5_0/lib/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
18:01:04,198 [main] WARN  NullpoMinoSlick: Cannot get driver informations
java.lang.UnsatisfiedLinkError: $PATH/NullpoMino7_5_0/lib/liblwjgl.so: $PATH/NullpoMino7_5_0/lib/liblwjgl.so: mauvaise classe ELF : ELFCLASS32 (Possible cause: architecture word width mismatch)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2649)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
        at java.base/java.lang.System.loadLibrary(System.java:1867)
        at org.lwjgl.Sys$1.run(Sys.java:73)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:82)
        at org.lwjgl.Sys.<clinit>(Sys.java:99)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:130)
        at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:233)
18:01:04,421 [main] FATAL NullpoMinoSlick: Game initialize failed (NON-SlickException)
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.Display
        at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
        at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:348)
```

## Java info

```console
$ java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```

**Comment by jpenguin** [comment]
ao far I can only get ./play_swing to run

**Comment by jpenguin** [comment]
OpenSUSE Tumbleweed
```
> ./NullpoMino         
14:33:28,788 [main] INFO  NullpoMinoSlick: NullpoMinoSlick Start
OpenJDK 64-Bit Server VM warning: You have loaded library /home/jpenguin/build/NullpoMino7_5_0/lib/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
14:33:28,855 [main] WARN  NullpoMinoSlick: Cannot get driver informations
java.lang.UnsatisfiedLinkError: /home/jpenguin/build/NullpoMino7_5_0/lib/liblwjgl.so: /home/jpenguin/build/NullpoMino7_5_0/lib/liblwjgl.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2659)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.lwjgl.Sys$1.run(Sys.java:73)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:82)
        at org.lwjgl.Sys.<clinit>(Sys.java:99)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:130)
        at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:233)
14:33:28,914 [main] FATAL NullpoMinoSlick: Game initialize failed (NON-SlickException)
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.Display
        at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
        at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:348)'

```
```
'> java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-suse-2.2-x8664)
OpenJDK 64-Bit Server VM (build 11.0.11+9-suse-2.2-x8664, mixed mode)
`
```

**Comment by TSTdoll** [comment]
Try OpenJDK 8

**Comment by jpenguin** [comment]
A while back, I got the SDL interface to work.  As I remember
Find a package with your same arch at https://pkgs.org/search/?q=sdljava
replace all available files in nullpomino/lib with the downloaded ones

Compiled GIT with fix libs https://u.pcloud.link/publink/show?code=XZSMHwXZutRI0ylKADupFFkERFv7CF8CHJTV
