### ISSUE TITLE
array out of bounds exception when more than 10 controllers detected

### ISSUE THREAD

**Issue by sandrin** [nullpomino/nullpomino#97]
log:

24-01-23 03:35:15,465 [main] INFO  mu.nu.nullpo.gui.slick.NullpoMinoSlick: NullpoMinoSlick Start
24-01-23 03:35:15,485 [main] INFO  mu.nu.nullpo.gui.slick.NullpoMinoSlick: Driver adapter:aticfx64, Driver version:8.17.10.1700
24-01-23 03:35:15,553 [main] INFO  Slick: Slick Build #229
24-01-23 03:35:15,553 [main] INFO  Slick: LWJGL Version: 2.6
24-01-23 03:35:15,553 [main] INFO  Slick: OriginalDisplayMode: 1920 x 1080 x 32 @500Hz
24-01-23 03:35:15,553 [main] INFO  Slick: TargetDisplayMode: 1280 x 960 x 0 @0Hz
24-01-23 03:35:15,830 [main] INFO  Slick: Starting display 1280x960
24-01-23 03:35:15,839 [main] INFO  Slick: Use Java PNG Loader = true
24-01-23 03:35:16,317 [main] INFO  Slick: Found 12 controllers
24-01-23 03:35:16,317 [main] INFO  Slick: 0 : HID-compliant consumer control device
24-01-23 03:35:16,317 [main] INFO  Slick: 1 : Tablet Monitor
24-01-23 03:35:16,317 [main] INFO  Slick: 2 : Tablet Monitor
24-01-23 03:35:16,317 [main] INFO  Slick: 3 : HID-compliant consumer control device
24-01-23 03:35:16,317 [main] INFO  Slick: 4 : DOIO
24-01-23 03:35:16,317 [main] INFO  Slick: 5 : DOIO
24-01-23 03:35:16,317 [main] INFO  Slick: 6 : Controller (Real Arcade Pro.4)
24-01-23 03:35:16,317 [main] INFO  Slick: 7 : WootingTwoHE
24-01-23 03:35:16,318 [main] INFO  Slick: 8 : Razer DeathAdder V3
24-01-23 03:35:16,318 [main] INFO  Slick: 9 : WootingTwoHE
24-01-23 03:35:16,318 [main] INFO  Slick: 10 : Razer DeathAdder V3
24-01-23 03:35:16,318 [main] INFO  Slick: 11 : HUION HID
24-01-23 03:35:16,380 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).MARATHON
24-01-23 03:35:16,381 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).LINE RACE
24-01-23 03:35:16,381 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).DIG RACE
24-01-23 03:35:16,381 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).DIG CHALLENGE
24-01-23 03:35:16,381 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).ULTRA
24-01-23 03:35:16,381 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).GRADE MANIA 3
24-01-23 03:35:16,381 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).SPEED MANIA 2
24-01-23 03:35:16,381 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).PRACTICE
24-01-23 03:35:16,381 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).GEM MANIA
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: (top-level).VS-BATTLE
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: STANDARD MODES.MARATHON
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: STANDARD MODES.MARATHON+
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: STANDARD MODES.EXTREME
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: STANDARD MODES.TECHNICIAN
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: RACE MODES.LINE RACE
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: RACE MODES.SCORE RACE
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: RACE MODES.DIG RACE
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: RACE MODES.COMBO RACE
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: RACE MODES.ULTRA
24-01-23 03:35:16,382 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.GRADE MANIA
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.GRADE MANIA 2
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.GRADE MANIA 3
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.SCORE ATTACK
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.SPEED MANIA
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.SPEED MANIA 2
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.GARBAGE MANIA
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.PHANTOM MANIA
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.FINAL
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.TIME ATTACK
24-01-23 03:35:16,383 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MANIA MODES.GEM MANIA
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: RETRO MODES.RETRO MARATHON
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: RETRO MODES.RETRO MASTERY
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: RETRO MODES.RETRO MANIA
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MISC MODES.SQUARE
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MISC MODES.DIG CHALLENGE
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MISC MODES.VS-BATTLE
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: MISC MODES.TOOL-VS MAP EDIT
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: AVALANCHE.AVALANCHE 1P (RC2)
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: AVALANCHE.AVALANCHE 1P FEVER MARATHON (RC2)
24-01-23 03:35:16,384 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: AVALANCHE.AVALANCHE VS-BATTLE (RC1)
24-01-23 03:35:16,385 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: AVALANCHE.AVALANCHE VS FEVER MARATHON (RC1)
24-01-23 03:35:16,385 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: AVALANCHE.AVALANCHE VS DIG RACE (RC1)
24-01-23 03:35:16,385 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: AVALANCHE.AVALANCHE VS BOMB BATTLE (RC1)
24-01-23 03:35:16,385 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: AVALANCHE.AVALANCHE-SPF VS-BATTLE (BETA)
24-01-23 03:35:16,385 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: PHYSICIAN.PHYSICIAN (RC1)
24-01-23 03:35:16,385 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: PHYSICIAN.PHYSICIAN VS-BATTLE (RC1)
24-01-23 03:35:16,385 [main] DEBUG mu.nu.nullpo.gui.slick.StateSelectModeFolder: SPF.SPF VS-BATTLE (BETA)
24-01-23 03:35:16,387 [main] INFO  mu.nu.nullpo.gui.slick.ControllerManager: Found 12 controllers from NullpoMinoSlick app
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:0, AxisCount:0, ButtonCount:31
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:1, AxisCount:0, ButtonCount:31
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:2, AxisCount:0, ButtonCount:3
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:3, AxisCount:0, ButtonCount:3
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:4, AxisCount:0, ButtonCount:31
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:5, AxisCount:0, ButtonCount:31
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:6, AxisCount:5, ButtonCount:10
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:7, AxisCount:0, ButtonCount:3
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:8, AxisCount:0, ButtonCount:31
24-01-23 03:35:16,387 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:9, AxisCount:0, ButtonCount:31
24-01-23 03:35:16,388 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:10, AxisCount:0, ButtonCount:3
24-01-23 03:35:16,388 [main] DEBUG mu.nu.nullpo.gui.slick.ControllerManager: ID:11, AxisCount:5, ButtonCount:7
24-01-23 03:35:16,390 [main] INFO  mu.nu.nullpo.gui.slick.ResourceHolder: Loading Image
24-01-23 03:35:16,392 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: 29 block skins found
24-01-23 03:35:16,392 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n0.png
24-01-23 03:35:16,396 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s0.png
24-01-23 03:35:16,397 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b0.png
24-01-23 03:35:16,401 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n1.png
24-01-23 03:35:16,402 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s1.png
24-01-23 03:35:16,403 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b1.png
24-01-23 03:35:16,404 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n2.png
24-01-23 03:35:16,405 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s2.png
24-01-23 03:35:16,405 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b2.png
24-01-23 03:35:16,407 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n3.png
24-01-23 03:35:16,407 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s3.png
24-01-23 03:35:16,408 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b3.png
24-01-23 03:35:16,409 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n4.png
24-01-23 03:35:16,410 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s4.png
24-01-23 03:35:16,411 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b4.png
24-01-23 03:35:16,412 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n5.png
24-01-23 03:35:16,413 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s5.png
24-01-23 03:35:16,413 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b5.png
24-01-23 03:35:16,415 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n6.png
24-01-23 03:35:16,415 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s6.png
24-01-23 03:35:16,416 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b6.png
24-01-23 03:35:16,417 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n7.png
24-01-23 03:35:16,418 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s7.png
24-01-23 03:35:16,419 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b7.png
24-01-23 03:35:16,420 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n8.png
24-01-23 03:35:16,420 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s8.png
24-01-23 03:35:16,421 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b8.png
24-01-23 03:35:16,422 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n9.png
24-01-23 03:35:16,425 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s9.png
24-01-23 03:35:16,426 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b9.png
24-01-23 03:35:16,432 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n10.png
24-01-23 03:35:16,433 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s10.png
24-01-23 03:35:16,434 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b10.png
24-01-23 03:35:16,436 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n11.png
24-01-23 03:35:16,437 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s11.png
24-01-23 03:35:16,438 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b11.png
24-01-23 03:35:16,440 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n12.png
24-01-23 03:35:16,441 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s12.png
24-01-23 03:35:16,442 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b12.png
24-01-23 03:35:16,443 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n13.png
24-01-23 03:35:16,444 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s13.png
24-01-23 03:35:16,445 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b13.png
24-01-23 03:35:16,448 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n14.png
24-01-23 03:35:16,449 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s14.png
24-01-23 03:35:16,450 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b14.png
24-01-23 03:35:16,451 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n15.png
24-01-23 03:35:16,452 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s15.png
24-01-23 03:35:16,453 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b15.png
24-01-23 03:35:16,454 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n16.png
24-01-23 03:35:16,455 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s16.png
24-01-23 03:35:16,456 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b16.png
24-01-23 03:35:16,457 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n17.png
24-01-23 03:35:16,458 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s17.png
24-01-23 03:35:16,459 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b17.png
24-01-23 03:35:16,460 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n18.png
24-01-23 03:35:16,461 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s18.png
24-01-23 03:35:16,462 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b18.png
24-01-23 03:35:16,463 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n19.png
24-01-23 03:35:16,464 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s19.png
24-01-23 03:35:16,465 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b19.png
24-01-23 03:35:16,466 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n20.png
24-01-23 03:35:16,467 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s20.png
24-01-23 03:35:16,467 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b20.png
24-01-23 03:35:16,469 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n21.png
24-01-23 03:35:16,470 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s21.png
24-01-23 03:35:16,470 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b21.png
24-01-23 03:35:16,471 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n22.png
24-01-23 03:35:16,474 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s22.png
24-01-23 03:35:16,475 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b22.png
24-01-23 03:35:16,477 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n23.png
24-01-23 03:35:16,478 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s23.png
24-01-23 03:35:16,479 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b23.png
24-01-23 03:35:16,481 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n24.png
24-01-23 03:35:16,481 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s24.png
24-01-23 03:35:16,482 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b24.png
24-01-23 03:35:16,483 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n25.png
24-01-23 03:35:16,484 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s25.png
24-01-23 03:35:16,485 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b25.png
24-01-23 03:35:16,485 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n26.png
24-01-23 03:35:16,486 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s26.png
24-01-23 03:35:16,487 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b26.png
24-01-23 03:35:16,488 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n27.png
24-01-23 03:35:16,491 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s27.png
24-01-23 03:35:16,492 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b27.png
24-01-23 03:35:16,500 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/normal/n28.png
24-01-23 03:35:16,502 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/small/s28.png
24-01-23 03:35:16,504 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/blockskin/big/b28.png
24-01-23 03:35:16,512 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/font.png
24-01-23 03:35:16,526 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/font_small.png
24-01-23 03:35:16,534 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/title.png
24-01-23 03:35:16,546 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/menu.png
24-01-23 03:35:16,550 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/frame.png
24-01-23 03:35:16,551 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/fieldbg2.png
24-01-23 03:35:16,554 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/fieldbg2_small.png
24-01-23 03:35:16,555 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/fieldbg2_big.png
24-01-23 03:35:16,560 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back0.png
24-01-23 03:35:16,573 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back1.png
24-01-23 03:35:16,584 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back2.png
24-01-23 03:35:16,593 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back3.png
24-01-23 03:35:16,603 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back4.png
24-01-23 03:35:16,615 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back5.png
24-01-23 03:35:16,625 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back6.png
24-01-23 03:35:16,635 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back7.png
24-01-23 03:35:16,645 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back8.png
24-01-23 03:35:16,655 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back9.png
24-01-23 03:35:16,665 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back10.png
24-01-23 03:35:16,678 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back11.png
24-01-23 03:35:16,688 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back12.png
24-01-23 03:35:16,700 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back13.png
24-01-23 03:35:16,710 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back14.png
24-01-23 03:35:16,723 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back15.png
24-01-23 03:35:16,732 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back16.png
24-01-23 03:35:16,742 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back17.png
24-01-23 03:35:16,752 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back18.png
24-01-23 03:35:16,762 [main] DEBUG mu.nu.nullpo.gui.slick.ResourceHolder: Loading image from res/graphics/back19.png
24-01-23 03:35:17,515 [main] INFO  Slick: Initialising sounds..
24-01-23 03:35:17,683 [main] INFO  Slick: - Sound works
24-01-23 03:35:17,684 [main] INFO  Slick: - 64 OpenAL source available
24-01-23 03:35:17,684 [main] INFO  Slick: - Sounds source generated
24-01-23 03:35:17,684 [main] INFO  mu.nu.nullpo.gui.slick.ResourceHolder: Loading Sound Effect
24-01-23 03:35:17,708 [main] ERROR Slick: 
java.lang.RuntimeException: Resource not found: res/se/move.wav
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at org.newdawn.slick.openal.SoundStore.getWAV(SoundStore.java:672)
	at org.newdawn.slick.Sound.<init>(Sound.java:60)
	at mu.nu.nullpo.gui.slick.SoundManager.load(SoundManager.java:82)
	at mu.nu.nullpo.gui.slick.ResourceHolder.load(ResourceHolder.java:204)
	at mu.nu.nullpo.gui.slick.StateLoading.enter(StateLoading.java:88)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:175)
	at org.newdawn.slick.ScalableGame.init(ScalableGame.java:69)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:394)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:357)
24-01-23 03:35:17,709 [main] ERROR mu.nu.nullpo.gui.slick.SoundManager: Failed to load wav file
org.newdawn.slick.SlickException: Failed to load sound: res/se/move.wav
	at org.newdawn.slick.Sound.<init>(Sound.java:70)
	at mu.nu.nullpo.gui.slick.SoundManager.load(SoundManager.java:82)
	at mu.nu.nullpo.gui.slick.ResourceHolder.load(ResourceHolder.java:204)
	at mu.nu.nullpo.gui.slick.StateLoading.enter(StateLoading.java:88)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:175)
	at org.newdawn.slick.ScalableGame.init(ScalableGame.java:69)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:394)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:357)
24-01-23 03:35:17,869 [main] FATAL mu.nu.nullpo.gui.slick.NullpoMinoSlick: Game initialize failed (NON-SlickException)
java.lang.ArrayIndexOutOfBoundsException: 10
	at org.newdawn.slick.Input.poll(Input.java:1314)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:635)
	at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:412)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:322)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:357)

this is caused by line 342 of Input.java from the slick2d library which declares an array with a size of 10, and then an if block starting on line 1309 that references every detected controller even if there are more than 10, resulting in an out of bounds exception

**Comment by sandrin** [comment]
my fork has this issue fixed, if anyone needs it:

https://github.com/sandrin/nullpomino
